"""initial schema

Revision ID: 3f7edd645b32
Revises: 
Create Date: 2026-09-09 07:23:58.714544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f7edd645b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('voice_guidelines', sa.Text(), nullable=False),
    sa.Column('brand_rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_table('failed_jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_jobs'))
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("agent IN ('triage', 'response', 'content', 'media')", name=op.f('ck_agent_runs_agent_allowed')),
    sa.CheckConstraint("status IN ('ok', 'error')", name=op.f('ck_agent_runs_status_allowed')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_agent_runs_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_brand_id'), 'agent_runs', ['brand_id'], unique=False)
    op.create_index('ix_agent_runs_entity', 'agent_runs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=False),
    sa.Column('analysis_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_assets_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_brand_id'), 'assets', ['brand_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.CheckConstraint("platform IN ('x', 'instagram', 'linkedin')", name=op.f('ck_platform_accounts_platform_allowed')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_platform_accounts_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_accounts'))
    )
    op.create_index(op.f('ix_platform_accounts_brand_id'), 'platform_accounts', ['brand_id'], unique=False)
    op.create_table('content_drafts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('hashtags_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.CheckConstraint("platform IN ('x', 'instagram', 'linkedin')", name=op.f('ck_content_drafts_platform_allowed')),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_content_drafts_status_allowed')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_content_drafts_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_content_drafts_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_drafts'))
    )
    op.create_index(op.f('ix_content_drafts_asset_id'), 'content_drafts', ['asset_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['platform_accounts.id'], name=op.f('fk_posts_account_id_platform_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('account_id', 'external_id', name=op.f('uq_posts_account_id_external_id'))
    )
    op.create_index(op.f('ix_posts_account_id'), 'posts', ['account_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('sentiment', sa.SmallInteger(), nullable=True),
    sa.Column('needs_reply', sa.Boolean(), nullable=True),
    sa.Column('urgency', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.CheckConstraint("category IS NULL OR category IN ('question', 'complaint', 'praise', 'spam', 'other')", name=op.f('ck_comments_category_allowed')),
    sa.CheckConstraint("status IN ('new', 'triaged', 'drafted', 'replied', 'failed')", name=op.f('ck_comments_status_allowed')),
    sa.CheckConstraint("urgency IS NULL OR urgency IN ('low', 'med', 'high')", name=op.f('ck_comments_urgency_allowed')),
    sa.CheckConstraint('sentiment BETWEEN -2 AND 2', name=op.f('ck_comments_sentiment_range')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    sa.UniqueConstraint('post_id', 'external_id', name=op.f('uq_comments_post_id_external_id'))
    )
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_comments_status'), 'comments', ['status'], unique=False)
    op.create_table('reply_drafts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'published')", name=op.f('ck_reply_drafts_status_allowed')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_reply_drafts_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name=op.f('fk_reply_drafts_comment_id_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_drafts'))
    )
    op.create_index(op.f('ix_reply_drafts_comment_id'), 'reply_drafts', ['comment_id'], unique=False)
    op.create_index(op.f('ix_reply_drafts_status'), 'reply_drafts', ['status'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reply_draft_id', sa.BigInteger(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reply_draft_id'], ['reply_drafts.id'], name=op.f('fk_outbox_reply_draft_id_reply_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox'))
    )
    op.create_index(op.f('ix_outbox_sent_at'), 'outbox', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_sent_at'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_reply_drafts_status'), table_name='reply_drafts')
    op.drop_index(op.f('ix_reply_drafts_comment_id'), table_name='reply_drafts')
    op.drop_table('reply_drafts')
    op.drop_index(op.f('ix_comments_status'), table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_account_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_content_drafts_asset_id'), table_name='content_drafts')
    op.drop_table('content_drafts')
    op.drop_index(op.f('ix_platform_accounts_brand_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_assets_brand_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_agent_runs_entity', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_brand_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('failed_jobs')
    op.drop_table('brands')
    # ### end Alembic commands ###
