"""insights

Revision ID: 792ac3d5d638
Revises: afa458b01da4
Create Date: 2026-09-11 08:37:04.587023

Also widens agent_runs.agent's CHECK to allow 'insight' (app/enums.py::AgentName).
Alembic's autogenerate does not diff CHECK constraint bodies — see afa458b01da4
for the same pattern when 'ideation' was added.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792ac3d5d638'
down_revision: Union[str, Sequence[str], None] = 'afa458b01da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f('ck_agent_runs_agent_allowed'), 'agent_runs', type_='check')
    op.create_check_constraint(
        op.f('ck_agent_runs_agent_allowed'),
        'agent_runs',
        "agent IN ('triage', 'response', 'content', 'media', 'ideation', 'insight')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_insights_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_insights_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_brand_id'), 'insights', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_brand_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###

    op.drop_constraint(op.f('ck_agent_runs_agent_allowed'), 'agent_runs', type_='check')
    op.create_check_constraint(
        op.f('ck_agent_runs_agent_allowed'),
        'agent_runs',
        "agent IN ('triage', 'response', 'content', 'media', 'ideation')",
    )
