"""content ideas

Revision ID: afa458b01da4
Revises: 4720ee0c2e61
Create Date: 2026-09-11 08:07:55.630486

Also widens agent_runs.agent's CHECK to allow 'ideation' (app/enums.py::AgentName).
Alembic's autogenerate does not diff CHECK constraint bodies, so this has to be
added by hand — it will not show up if you regenerate this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa458b01da4'
down_revision: Union[str, Sequence[str], None] = '4720ee0c2e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint(op.f('ck_agent_runs_agent_allowed'), 'agent_runs', type_='check')
    op.create_check_constraint(
        op.f('ck_agent_runs_agent_allowed'),
        'agent_runs',
        "agent IN ('triage', 'response', 'content', 'media', 'ideation')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_ideas',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('brand_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_signal', sa.String(length=255), nullable=True),
    sa.Column('agent_run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='proposed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'approved', 'rejected')", name=op.f('ck_content_ideas_status_allowed')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_content_ideas_agent_run_id_agent_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_content_ideas_brand_id_brands'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_ideas'))
    )
    op.create_index(op.f('ix_content_ideas_brand_id'), 'content_ideas', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_ideas_brand_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    # ### end Alembic commands ###

    op.drop_constraint(op.f('ck_agent_runs_agent_allowed'), 'agent_runs', type_='check')
    op.create_check_constraint(
        op.f('ck_agent_runs_agent_allowed'),
        'agent_runs',
        "agent IN ('triage', 'response', 'content', 'media')",
    )
