"""The storage boundary (hard rule #9).

`LocalDiskStorage` is the only thing in Phase 1 that touches a path, and it is
handed keys that were read back out of the database or off a URL. These tests
are mostly about that: what happens when the key is not one we generated.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from worker.storage import LocalDiskStorage, StorageError, build_storage, new_key, validate_key


@pytest.fixture
def storage(tmp_path: Path) -> LocalDiskStorage:
    return LocalDiskStorage(tmp_path)


async def test_put_then_get_round_trips(storage: LocalDiskStorage) -> None:
    key = await storage.put("brands/1/abc.png", b"\x89PNG bytes")

    assert key == "brands/1/abc.png"
    assert await storage.get(key) == b"\x89PNG bytes"


async def test_put_creates_missing_directories(storage: LocalDiskStorage) -> None:
    """The brand prefix means the first upload for a brand has no directory yet."""
    await storage.put("brands/99/deep/nested/x.jpg", b"data")

    assert (storage.root / "brands/99/deep/nested/x.jpg").read_bytes() == b"data"


async def test_put_leaves_no_partial_file_behind(storage: LocalDiskStorage) -> None:
    """Written to a temp name and renamed into place.

    The worker picks the job up from Redis in milliseconds, so on a 4 MB upload
    a reader can genuinely arrive mid-write. Rename is atomic on one filesystem;
    a plain write is not.
    """
    await storage.put("brands/1/a.png", b"x" * 4096)

    leftovers = [p.name for p in (storage.root / "brands/1").iterdir() if p.name.startswith(".")]
    assert leftovers == []


async def test_get_reports_a_missing_object(storage: LocalDiskStorage) -> None:
    with pytest.raises(StorageError, match="No object at"):
        await storage.get("brands/1/never-written.png")


async def test_delete_is_idempotent(storage: LocalDiskStorage) -> None:
    """Deleting twice must not raise: a cleanup path that can fail is a cleanup
    path that gets wrapped in try/except at every call site."""
    await storage.put("brands/1/a.png", b"data")

    await storage.delete("brands/1/a.png")
    await storage.delete("brands/1/a.png")

    assert not (storage.root / "brands/1/a.png").exists()


def test_url_is_an_address_the_browser_can_use(storage: LocalDiskStorage) -> None:
    assert storage.url("brands/1/abc.png") == "/assets/file/brands/1/abc.png"


# --- keys that are not ours ------------------------------------------------


@pytest.mark.parametrize(
    "key",
    [
        "../../etc/passwd",
        "brands/../../etc/passwd",
        "/etc/passwd",
        "brands/1/../../../root/.ssh/id_rsa",
        "..",
        "",
        "brands\\1\\a.png",
        "brands/1/a\x00.png",
    ],
)
def test_a_traversing_key_is_refused(key: str) -> None:
    """Every key is generated by `new_key` today. That is exactly the assumption
    that makes a traversal bug ship, so it is checked at the boundary — the file
    route takes a key straight off a URL."""
    with pytest.raises(StorageError):
        validate_key(key)


async def test_a_traversing_key_never_reaches_the_filesystem(
    storage: LocalDiskStorage, tmp_path: Path
) -> None:
    outside = tmp_path.parent / "escaped.txt"

    with pytest.raises(StorageError):
        await storage.put("../escaped.txt", b"owned")

    assert not outside.exists()


# --- key generation --------------------------------------------------------


def test_new_key_is_unique_per_upload() -> None:
    """Two people uploading photo.jpg must not collide."""
    first = new_key(1, "photo.jpg")
    second = new_key(1, "photo.jpg")

    assert first != second
    assert first.startswith("brands/1/")
    assert first.endswith(".jpg")


def test_new_key_does_not_put_the_uploaded_filename_in_the_path() -> None:
    """The name is attacker-controlled input; it stays on assets.filename for
    display and never becomes part of a path."""
    key = new_key(1, "../../etc/passwd")

    assert "passwd" not in key
    assert validate_key(key) == key


def test_new_key_drops_an_implausible_extension() -> None:
    """A key is also a URL path segment, so only a short alphanumeric suffix
    survives. Anything else is dropped rather than sanitised: the extension is
    decoration, and `assets.mime` is what the file route actually serves with.
    """
    key = new_key(1, "payload.php.jpg?x=1")

    assert key.startswith("brands/1/")
    assert "?" not in key
    assert validate_key(key) == key


def test_build_storage_rejects_an_unknown_backend() -> None:
    """STORAGE_BACKEND is typed as Literal['local'] in config, so this is the
    second line of defence rather than the first."""
    with pytest.raises(StorageError, match="Unknown STORAGE_BACKEND"):
        build_storage("s3", "/tmp")
