"""Binary storage behind one interface (hard rule #9).

Nothing outside this module opens a file or builds a path. Phase 1 writes to a
local disk volume; Phase 4 writes to S3. That swap is meant to be a new subclass
plus an env change, and it only stays that way if every caller goes through
`StorageBackend`.

**Why this lives in the api package and not `worker/`.** Both services touch the
same bytes: the API writes an upload, the worker reads it back to send to the
vision model. Two implementations of "what does a storage_key mean on disk"
would drift, and the one that drifts is the one only the media path exercises —
once per demo. So it is defined once here and copied into the worker image at
build time, exactly as the SQLAlchemy models are (D24).
`worker/worker/storage.py` re-exports it and resolves the worker's own config.

**Why the interface is async.** Local disk does not need it. S3 does, and the
whole point of the interface is that Phase 4 changes no call sites. A sync
interface now means editing every `await`-less caller later, which is the cost
hard rule #9 exists to avoid. `url()` stays sync because neither backend does
I/O to produce one — presigning is local computation.
"""

from __future__ import annotations

import asyncio
import mimetypes
import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any
from uuid import uuid4

import boto3
from botocore.config import Config
from botocore.exceptions import ClientError

# The API route that serves a locally-stored file.
#
# A local disk has no address a browser can reach, so `LocalDiskStorage.url()`
# has to name the one thing that can serve the bytes. Defined here and imported
# by the router so the two cannot drift. In Phase 4 `S3Storage.url()` returns a
# presigned URL instead and this route goes away — the web app never learns
# which backend it is talking to, which is the point.
ASSET_FILE_ROUTE = "/assets/file"

# How long a presigned S3 link stays valid. One hour: long enough for a slow page
# and a reviewer who leaves the tab open, short enough that a leaked link dies.
PRESIGNED_URL_TTL_SECONDS = 3600

# The only Content-Types S3Storage will store an object under. The upload route's
# own allowlist (ALLOWED_MIME in routers/assets.py), repeated here because this
# module is also the worker's and must not import a router.
SERVABLE_IMAGE_TYPES = frozenset({"image/png", "image/jpeg", "image/webp"})

# Conservative on purpose: a storage key is also a URL path segment and a
# filesystem path, so it may contain only what is unambiguous in both.
_SAFE_KEY = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/-]*$")


class StorageError(RuntimeError):
    """Raised for a key that is missing or not addressable in this backend."""


class StorageBackend(ABC):
    """The four operations from hard rule #9, and no others.

    Keeping the surface this small is what makes the S3 implementation short
    enough to be obviously correct.
    """

    @abstractmethod
    async def put(self, key: str, data: bytes) -> str:
        """Store `data` at `key` and return the key."""

    @abstractmethod
    async def get(self, key: str) -> bytes:
        """Read back what `put` stored. Raises StorageError if absent."""

    @abstractmethod
    def url(self, key: str) -> str:
        """An address a browser can fetch. No I/O."""

    @abstractmethod
    async def delete(self, key: str) -> None:
        """Remove the object. Absent is not an error — delete is idempotent."""


def validate_key(key: str) -> str:
    """Reject anything that could escape the storage root.

    Keys are generated by `new_key`, so today every value is ours. But the media
    node reads a key back out of the database and the file route takes one
    straight off a URL, and "it is always ours" is exactly the assumption that
    makes a traversal bug ship. Checked at the boundary instead: no leading
    slash, no `..`, no backslashes, no NUL.
    """
    if not key or not _SAFE_KEY.match(key) or ".." in key.split("/"):
        raise StorageError(f"Unsafe storage key: {key!r}")
    return key


def new_key(brand_id: int, filename: str) -> str:
    """A fresh key for an upload: `brands/<brand_id>/<uuid><ext>`.

    The name the user uploaded is kept on `assets.filename` for display and
    deliberately not used in the key — two people uploading `photo.jpg` must not
    collide, and a filename is attacker-controlled input that would otherwise
    reach a path. The brand prefix means "delete a brand's assets" stays one
    prefix scan on S3 too.
    """
    suffix = Path(filename).suffix.lower()
    extension = suffix if re.fullmatch(r"\.[a-z0-9]{1,8}", suffix) else ""
    return f"brands/{brand_id}/{uuid4().hex}{extension}"


class LocalDiskStorage(StorageBackend):
    """Phase 1: a directory on a Docker volume."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / validate_key(key)).resolve()
        # Belt and braces. validate_key already rejects traversal, but a symlink
        # inside the root could still point outside it, and this check costs one
        # comparison against a resolved path.
        if not path.is_relative_to(self.root):
            raise StorageError(f"Key escapes the storage root: {key!r}")
        return path

    async def put(self, key: str, data: bytes) -> str:
        path = self._path(key)

        def write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write-then-rename, so a reader never sees a half-written image.
            # The worker picks the job up from Redis the moment the API commits,
            # and on a 4 MB upload that race is wide enough to hit.
            temporary = path.with_name(f".{path.name}.{uuid4().hex}.part")
            temporary.write_bytes(data)
            temporary.replace(path)

        await asyncio.to_thread(write)
        return key

    async def get(self, key: str) -> bytes:
        path = self._path(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except FileNotFoundError as exc:
            raise StorageError(f"No object at {key!r}") from exc

    def url(self, key: str) -> str:
        return f"{ASSET_FILE_ROUTE}/{validate_key(key)}"

    async def delete(self, key: str) -> None:
        path = self._path(key)
        await asyncio.to_thread(path.unlink, True)


def s3_client(region: str) -> Any:
    """An S3 client configured for presigning, not just for calls.

    Both settings are load-bearing. Left to its defaults, boto3 presigns with the
    legacy SigV2 scheme, which regions opened since 2014 (us-east-2 among them)
    reject outright. Virtual-hosted addressing is what AWS recommends for presigned
    links. The region is passed in rather than read from the environment because
    boto3 reads AWS_DEFAULT_REGION, while ECS and Terraform set AWS_REGION.
    Credentials are left to boto3's chain: the task role on ECS.

    A private Session, not `boto3.client()`: that shares one module-global session,
    and sessions are not thread-safe. The finished client is, so callers build it
    once at startup and share it.
    """
    return boto3.session.Session().client(
        "s3",
        region_name=region,
        config=Config(signature_version="s3v4", s3={"addressing_style": "virtual"}),
    )


class S3Storage(StorageBackend):
    """Phase 4: one private bucket. `STORAGE_ROOT` is its name.

    boto3 is synchronous, so each call runs in a worker thread, the same way
    `LocalDiskStorage` keeps disk I/O off the event loop. The client is passed in
    rather than built here: `build_storage` owns the region and signing config, and
    the tests hand in a stubbed client.
    """

    def __init__(self, bucket: str, client: Any) -> None:
        self.bucket = bucket
        self._client = client

    async def put(self, key: str, data: bytes) -> str:
        # Content-Type is stored with the object because a presigned URL serves
        # it straight to the browser. Only the image types the upload route
        # accepts are labelled as such: the extension comes from the uploader's
        # filename, and an object stored as text/html or image/svg+xml would run
        # in the browser from our bucket. Anything else is served as a download.
        guessed = mimetypes.guess_type(validate_key(key))[0]
        content_type = guessed if guessed in SERVABLE_IMAGE_TYPES else "application/octet-stream"
        await asyncio.to_thread(
            self._client.put_object,
            Bucket=self.bucket,
            Key=key,
            Body=data,
            ContentType=content_type,
        )
        return key

    async def get(self, key: str) -> bytes:
        def read() -> bytes:
            try:
                response = self._client.get_object(Bucket=self.bucket, Key=validate_key(key))
            except ClientError as exc:
                # Only "not there" becomes StorageError. Access denied or a
                # throttle is a real fault and propagates, so arq retries it
                # instead of the caller treating it as a missing image.
                if exc.response.get("Error", {}).get("Code") in ("NoSuchKey", "404"):
                    raise StorageError(f"No object at {key!r}") from exc
                raise
            body: bytes = response["Body"].read()
            return body

        return await asyncio.to_thread(read)

    def url(self, key: str) -> str:
        # Signed with whatever credentials built the client: the ECS task role in
        # Phase 4. A fresh link is minted on every API response, so the expiry
        # only has to outlive one page view, not a bookmark.
        url: str = self._client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": validate_key(key)},
            ExpiresIn=PRESIGNED_URL_TTL_SECONDS,
        )
        return url

    async def delete(self, key: str) -> None:
        # Idempotent for free: S3 answers 204 whether or not the key existed.
        await asyncio.to_thread(
            self._client.delete_object, Bucket=self.bucket, Key=validate_key(key)
        )


def build_storage(backend: str, root: str, region: str | None = None) -> StorageBackend:
    """Backend name -> implementation.

    Takes the values rather than reading config, because the API and the worker
    each read their own environment (D22) and this is the one piece both of them
    share. For S3, `root` is the bucket name: Terraform passes it as STORAGE_ROOT.
    """
    if backend == "local":
        return LocalDiskStorage(root)
    if backend == "s3":
        if not region:
            raise StorageError("STORAGE_BACKEND=s3 needs AWS_REGION")
        return S3Storage(root, s3_client(region))
    raise StorageError(f"Unknown STORAGE_BACKEND: {backend!r}")
